language: node_js

before_install:
  - mkdir .hugo
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-32bit.tar.gz | tar -xvz -C ./.hugo
  - export PATH="$(pwd)/.hugo:$PATH"
  - hugo version

script: npm run components:test

after_success: 
 - npm run build
 - ls -la dist 

cache: npm


