baseurl         = "/"
languageCode    = "en-GB"
disqusShortname = ""
paginate        = 7
#SectionPagesMenu = "main"
canonifyurls    = true
title       = "MountainDev"
[params]
  title       = "MountainDev"
  subtitle    = "I write typos and sometimes code by mistake"
  copyright   = "© 2018"

  description = "Matteo Hertel's blog, will talk about latest technologies, general fullstack tutorials and much more"
  metaDescription = "Matteo Hertel's blog, will talk about latest technologies, general fullstack tutorials and much more"
  cover = "https://res.cloudinary.com/demo/image/gravatar/d_identicon,w_250,f_auto,q_auto/53d2fe0924a9b4e167e21ef356e09e89.jpg"
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "MHDev91"
  githubName = "matteo-hertel"
  linkedinName = "hertelmatteo"
  mediumName = ""

  logo = "logo/animated_logo.svg"
  orgName = "MH"
  orgWebsite = "https://matteohertel.com"

  showSupport = true

  author = "Matteo Hertel"
  authorAvatar = "https://res.cloudinary.com/demo/image/gravatar/d_identicon,w_150,f_auto,q_auto/53d2fe0924a9b4e167e21ef356e09e89.jpg"
  authorLocation = "London, UK"
  authorWebsite = "https://matteohertel.com"
  authorDescription = "I write typos and sometimes code by mistake"

  pageNotFoundTitle = "404 - Move along, nothing to see here"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99
