baseurl         = "/"
theme           = "slimer"
languageCode    = "en-GB"
disqusShortname = ""
paginate        = 7
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Slimer"
  subtitle    = ""
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "matteo-hertel"
  linkedinName = "hertelmatteo"
  mediumName = ""

  logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "London, UK"
  authorWebsite = "https://matteohertel.com"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


