/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface FloatingHeader {
    /**
    * The trigger treshold to activate the floating header
    */
    'activeClassName': string;
    /**
    * The trigger treshold to activate the floating header
    */
    'triggerTreshold': number;
  }
  interface FloatingHeaderAttributes extends StencilHTMLAttributes {
    /**
    * The trigger treshold to activate the floating header
    */
    'activeClassName'?: string;
    /**
    * The trigger treshold to activate the floating header
    */
    'triggerTreshold'?: number;
  }

  interface GitEdit {
    /**
    * The file path in the repo
    */
    'filePath': string;
    'large': boolean;
    /**
    * The repo base url
    */
    'repo': string;
  }
  interface GitEditAttributes extends StencilHTMLAttributes {
    /**
    * The file path in the repo
    */
    'filePath'?: string;
    'large'?: boolean;
    /**
    * The repo base url
    */
    'repo'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'FloatingHeader': Components.FloatingHeader;
    'GitEdit': Components.GitEdit;
  }

  interface StencilIntrinsicElements {
    'floating-header': Components.FloatingHeaderAttributes;
    'git-edit': Components.GitEditAttributes;
  }


  interface HTMLFloatingHeaderElement extends Components.FloatingHeader, HTMLStencilElement {}
  var HTMLFloatingHeaderElement: {
    prototype: HTMLFloatingHeaderElement;
    new (): HTMLFloatingHeaderElement;
  };

  interface HTMLGitEditElement extends Components.GitEdit, HTMLStencilElement {}
  var HTMLGitEditElement: {
    prototype: HTMLGitEditElement;
    new (): HTMLGitEditElement;
  };

  interface HTMLElementTagNameMap {
    'floating-header': HTMLFloatingHeaderElement
    'git-edit': HTMLGitEditElement
  }

  interface ElementTagNameMap {
    'floating-header': HTMLFloatingHeaderElement;
    'git-edit': HTMLGitEditElement;
  }


}
