/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface FloatingHeader {
    /**
    * The trigger treshold to activate the floating header
    */
    'activeClassName': string;
    /**
    * The trigger treshold to activate the floating header
    */
    'triggerTreshold': number;
  }
  interface FloatingHeaderAttributes extends StencilHTMLAttributes {
    /**
    * The trigger treshold to activate the floating header
    */
    'activeClassName'?: string;
    /**
    * The trigger treshold to activate the floating header
    */
    'triggerTreshold'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'FloatingHeader': Components.FloatingHeader;
  }

  interface StencilIntrinsicElements {
    'floating-header': Components.FloatingHeaderAttributes;
  }


  interface HTMLFloatingHeaderElement extends Components.FloatingHeader, HTMLStencilElement {}
  var HTMLFloatingHeaderElement: {
    prototype: HTMLFloatingHeaderElement;
    new (): HTMLFloatingHeaderElement;
  };

  interface HTMLElementTagNameMap {
    'floating-header': HTMLFloatingHeaderElement
  }

  interface ElementTagNameMap {
    'floating-header': HTMLFloatingHeaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
